# Generated by Django 4.1.7 on 2023-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientaddress',
            old_name='pat_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='patientaddress',
            name='role',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
