# Generated by Django 4.1.7 on 2023-03-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_rename_pat_address_patientaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
