# Generated by Django 4.1.7 on 2023-03-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_patientaddress_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
