# Generated by Django 4.1.7 on 2023-03-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_patientaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaddress',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
